tests/test_sheet.py, xlrd/sheet.py
This will return a generator providing each row in the workbook. This is useful, for instance, when using `map` to map a function to each row.
As a secondary note, shouldn't these comments be docstrings? It'd make this tool a lot easier to use from the shell.
=> Add method to get generator for iterating rows.

README.md, tox.ini
The README had an outdated list of supported python version. Tox.ini didn't have an envlist at all.
I used the versions listed in .travis.yaml for both.
=> Update supported pythons

tests/test_sheet.py, xlrd/sheet.py
Fixes a bug for ragged_rows=False when merged cells increases the number of columns in the sheet. This requires all rows to be extended to ensure equal row lengths that match the number of columns in the sheet.
Resolves issues #113 and #129.
=> Fix unequal row lengths.

tests/test_cell.py, xlrd/sheet.py
Current situation: Empty cell value is a bytestring on Python2 and a
unicode string on Python3.
=> Uniform empty cell value (always unicode string) for Python2 and Python3 #159

xlrd/sheet.py
I'm working with some old third-party software that outputs its own flavor of .xls. A sample file can be downloaded with:
```
wget https://www.dropbox.com/s/japk6uv4u1js7sz/xlrd_test.XLS 
```
To replicate:
```python
import xlrd
wb = xlrd.open_workbook("xlrd_test.XLS", encoding_override="latin-1", verbosity=1)
```
Stack trace:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-22e058971f78> in <module>()
----> 1 wb = xlrd.open_workbook("xlrd_test.XLS", encoding_override="latin-1", verbosity=1)
/home/patrick/miniconda3/lib/python3.4/site-packages/xlrd/__init__.py in open_workbook(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, …
```
=> NoneType zoom variable causes crash

xlrd/sheet.py
It's in the code fragment, but it's not obvious from the text.
=> Document chi, rhi in merged cells are exclusive

xlrd/xlsx.py
Note that this pull request is missing tests, but I want first to check that my approach is fine. The problem is that some xlsx files have the following start:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheetPr filterMode="false">
<pageSetUpPr fitToPage="false"/>
</sheetPr>
<dimension ref="1:49"/>
<sheetViews>
<sheetView colorId="64" defaultGridColor="true" rightToLeft="false" showFormulas="false" showGridLines="true" showOutlineSymbols="true" showRowColHeaders="true" showZeros="true">
<selection activeCell="A29" activeCellId="0" pane="topLeft" sqref="A29"/>
</sheetView>
</sheetViews>
<cols>
<col collapsed="false" …
```
=> Fix parsing dimensions in xlsx files

xlrd/xlsx.py
I've seen a few instances where we get a single cell merge showing up in documents, excel opens them correctly however xlrd will crash with a ValueError in 0.9.3.
=> [hotfix] do-merge-single-cell

docs/changes.rst
`xldate_to_datetime()` does not exist: it is named `xldate_as_datetime` in the xldate.py file.
I lost 5min to search for the function by name, so it might be useful for anyone else :-)
=> Update changes.rst to fix a typo in method name

xlrd/sheet.py
Report cell in R1C1 format that can be directly pasted into Excel's "Name field" (top left corner), allowing to jump directly to the cell.
before:
``
*** WARNING: hyperlink at r=5116 c=93 has 174 extra data bytes:
``
after:
``
*** WARNING: hyperlink at R5116C93 has 174 extra data bytes:
``
=> report error in R1C1 syntax

.gitignore, .travis.yml, docs/changes.rst, docs/references.rst, tox.ini, xlrd/__init__.py
Many editors clean up trailing white space on save. By removing it all
in one go, it helps keep future diffs cleaner by avoiding spurious white
space changes on unrelated lines.
=> Trim trialing white space throughout the project

.travis.yml, requirements.txt
Removes duplication of testing environments. Testing locally with tox now better matches the Travis CI environment.
=> Run Travis CI through tox configuration

xlrd/compdoc.py, xlrd/formatting.py, xlrd/sheet.py
More forward compatible with modern Python 3 syntax.
=> Use Unicode literals throughout project; drop u str prefix

docs/vulnerabilities.rst
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
=> Update pypi.python.org URL to pypi.org

xlrd/book.py
time.clock() is deprecated and won't work on 3.8. time.perf_counter() should be able to do the job here.
=> MAINT: time.clock->time.perf_counter closes #294

xlrd/book.py
This change will increase the encoding compatibility. It has been used on a lot of documents from all over the world.
=> Change to default encodings and codepages, for better compatibility

.travis.yml, tests/test_sheet.py, tests/test_workbook.py, xlrd/book.py, xlrd/sheet.py
Hi, I recently had to work with `xlrd` and found parts of it a bit counter-intuitive and needing to pore over the syntax given the lack of support for any magic methods.
Things that seem intuitive like `for sheet in book.sheets()` actually loads everything at once instead of as they're needed, and instead we should be doing `for book.sheet_by_index(i) for i in book.nsheets` which is not something I'd have done without looking at source.
Similarly iterating through rows, I find this show up on stackoverflow`[sh.row_values(rownum) for rownum in range(sh.nrows)]` when it could be `[row for row in sh.get_rows()]`. But this is non-obvious and people are sticking with what works first as there are a lot of methods to be looked at.
Getting rows has `sh.row(rowidx)` and for cells it's …
=> Make `Sheet` and `Book` more Pythonic and add tests

xlrd/xlsx.py
This causes errors to be lost as the error handling code attempts to access the logfile:
```
File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 253, in cell
self.dump(self.book.logfile,
AttributeError: 'NoneType' object has no attribute 'logfile'
```
See for example https://stackoverflow.com/questions/24437009/python-xlrd-named-range-value/28171108
=> Fix typo of field "book"

xlrd/book.py
Strip spaces from last author to deal with malformed author fields.
I realise that it would be better to fix the source docs, but these are third party docs and we don't have the option to fix them at source.
=> Strip non unicode spaces from last author

xlrd/sheet.py
There is a small typo in xlrd/sheet.py.
Should read `optimisation` rather than `optmisation`.
=> Fix simple typo: optmisation -> optimisation

README.rst
Adding an indication that this project is available on pypi.
Specifically; it is helpful to indicate *which* pypi package should be used (as there are several, potentially nefarious clones).
=> Indicate which pypi package is the official one.
